[server]
port = 8600
baseUrlPath = "/db-editor"  # App url will be https://<host><baseUrlPath>/
enableWebsocketCompression = false
#address = "127.0.0.1"          # Brock direct access

[info]
app_name = "DB Editor"                   # If blank, displayed name will be determined from baseUrlPath
description = ""
intended_users = ""
developer = "Tomoo Mari"
email = ""                      # If blank, "<FirstName>.<LastName>@skyworksinc.com" will be set
test = false                    # If true, your app will be displayed as a test app
visible = true                  # If false, your app will not be displayed